language: python
python: 3.6
cache: pip

dist: xenial

jobs:
  include:
    -
      env:
        JOB="static"
    -
      env:
        JOB="tests"

before_install:
  - pip install pip --upgrade
  - pip freeze

install:
  - if [[ "$JOB" == "static" ]]; then
      pip install black;
    fi
  - if [[ "$JOB" == "tests" ]]; then
      pip install -e .[tests];
    fi

script:
  - if [[ "$JOB" == "static" ]]; then
      black --check .;
    fi
  - if [[ "$JOB" == "tests" ]]; then
      py.test;
    fi
